name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - Main
      - Live
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'Live' && 'Live' || 'Dev' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      - run: npm install

      - name: Set environment variables globally
        run: |
          echo "VITE_fbApiKey=${{ secrets.VITE_fbApiKey }}" >> $GITHUB_ENV
          echo "VITE_fbAuthDomain=${{ secrets.VITE_fbAuthDomain }}" >> $GITHUB_ENV
          echo "VITE_fbDatabaseURL=${{ secrets.VITE_fbDatabaseURL }}" >> $GITHUB_ENV
          echo "VITE_fbProjectID=${{ secrets.VITE_fbProjectID }}" >> $GITHUB_ENV
          echo "VITE_fbStorageBucket=${{ secrets.VITE_fbStorageBucket }}" >> $GITHUB_ENV
          echo "VITE_fbMessagingSenderID=${{ secrets.VITE_fbMessagingSenderID }}" >> $GITHUB_ENV
          echo "VITE_fbAppID=${{ secrets.VITE_fbAppID }}" >> $GITHUB_ENV
          echo "VITE_ReCaptchaKey=${{ secrets.VITE_ReCaptchaKey }}" >> $GITHUB_ENV
          echo "VITE_measurementID=${{ secrets.VITE_measurementID }}" >> $GITHUB_ENV
          echo "VITE_APIURL=${{ secrets.VITE_APIURL }}" >> $GITHUB_ENV
          echo "VITE_SENTRY_PROJECT=${{ secrets.VITE_SENTRY_PROJECT }}" >> $GITHUB_ENV
          echo "VITE_eveClientID=${{ secrets.VITE_eveClientID }}" >> $GITHUB_ENV
          echo "VITE_eveSecretKey=${{ secrets.VITE_eveSecretKey }}" >> $GITHUB_ENV
          echo "VITE_eveCallbackURL=${{ secrets.VITE_eveCallbackURL }}" >> $GITHUB_ENV
          echo "VITE_eveScope=${{ secrets.VITE_eveScope }}" >> $GITHUB_ENV

      - run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          channelId: "${{ github.ref_name == 'Live' && github.ref_name || 'Live' }}"
          projectId: "${{ secrets.VITE_fbProjectID }}"
